#name = "claude-code-proxy"
name = "claude-proxy"
main = "src/index.ts"
compatibility_date = "2024-03-20"

[vars]
HAIKU_MODEL_NAME= "快速的模型"
HAIKU_BASE_URL= "https://url/v1"
HAIKU_API_KEY= "sk-**"

[observability.logs]
enabled = true
